live_config_reload = true

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85

# [window.padding]
# x = 18
# y = 16
